spring.datasource.url: jdbc:mysql://localhost:3306/finance_tracker_db
spring.datasource.username: springstudent
spring.datasource.password: springstudent

#  db update strategy
spring.jpa.hibernate.ddl-auto: update
