spring.datasource.url: jdbc:mysql://localhost:3306/finance_tracker_db
spring.datasource.username: springstudent
spring.datasource.password: springstudent

#  db create delete strategy
spring.jpa.hibernate.ddl-auto: update

# logging

logging.level.org.hibernate.SQL: warn
